channels:
  - conda-forge
  - terradue
dependencies:
  - python=3.8
  - numpy
  - jupyter-server-proxy
  - code-server >=3.2
  - awscli
  - cwltool
  - stars
  - mamba 
  - pip
  - yq
  - jq
  - awscli
  - gdal
  - click 
  - pystac
  - localtileserver
  - nodejs
  - ipyleaflet
  - pip:
    - nbgitpuller
