#!/bin/bash

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --py jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy
jupyter lab build

code-server --install-extension ms-python.python 
code-server --install-extension redhat.vscode-yaml
code-server --install-extension sbg-rabix.benten-cwl

# Install the VS code proxy
pip install -e.

mamba create -c conda-forge -p /srv/conda/envs/env_docs  mkdocs-material && /srv/conda/envs/env_docs/bin/pip3 install mkdocs-mermaid2-plugin
mamba clean --all -f -y
